openapi: "3.0.0"
info:
  title: Create an employees API
  version: "1.0.0"
paths:
  /employees/{empId}:
    get:
      tags:
        - Employees
      description: API for returning employees by Id MongoDB Atlas.
      summary: returns a employees first name last name and empId with a valid id.
      parameters:
        - name: empId
          in: path
          required: true
          description: The employee Id requested by the user.
          schema:
            type: number
      responses:
        "200":
          description: Composer Documents
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
# Operations Description
# First create the employees API goals, what the goal/description of each API should do and what they need
# Second create a table that shows the API requirements, this will include operation, HTTP Protocol, parameters, data type and path
# Third create a YAML file using swagger
# -using the information from the previous weeks to file out the swagger program and saving it as YAML
# -validate YAML file
