openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
info:
  description: This is a simple API
  version: "1.0.0"
  title: employees API
paths:
  /api/employees/{empId}:
    get:
      tags:
        - employees
      summary: find employee by id
      operationId: findEmployeeById
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: path
          name: empId
          description: pass in the required employee id
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Employee document found
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Server exception
        "501":
          description: MongoDB Exception
# Operations Description
# First create the employees API goals, what the goal/description of each API should do and what they need
# Second create a table that shows the API requirements, this will include operation, HTTP Protocol, parameters, data type and path
# Third create a YAML file using swagger
# -using the information from the previous weeks to file out the swagger program and saving it as YAML
# -validate YAML file
